### ISSUE TITLE
Request for the Image File

### ISSUE THREAD

**Issue by nyh-a** [DarthZhu/VTE#2]
Hi there,

I am currently working on a project related to taxonomy expansion. I recently read your paper and found it extremely insightful.

I am writing to kindly request permission to use the images in your paper which you said you would upload soon.

Thank you for considering my request. I greatly appreciate your contribution to the field, and I look forward to hearing from you.

**Comment by DarthZhu** [comment]
Hi,

Thanks for your interest in our work!

We release the images for the SemEval dataset [here](https://drive.google.com/drive/folders/19dNsBkpxH4LD7ivz9toqNOMbv304edkI?usp=sharing).

In terms of the images used for the Chinese Taxonomy dataset, due to the commercial license, we cannot open-source them. If you would like to use the dataset, it is possible to search each term on the search engine, e.g. Google, to get access to its image. Sorry for the inconvenience. 

If you have any further questions, please feel free to contact me.
